name: Lint

on: pull_request

jobs:
  lint-protos:
    name: Lint protobuf definitions
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1

      # Lint your Protobuf sources
      - uses: bufbuild/buf-lint-action@v1

      # Check breaking changes
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: "https://github.com/GiganticMinecraft/SeichiGameAPI-protocol.git#branch=main"
